### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DervisevicAdnan** [DervisevicAdnan/chess#1]
- [ ] #2
- [ ] Razvijati logiku igre
- [ ] Testirati na igrama
- [ ] Napraviti frontend, backend i povezati sa engine-om
